---
- name: Setup DBserver
  hosts: dbservers
  vars:
    dbname: accounts
    dbuser: vprofile
    dbpass: vprofile123
  tasks:
    - name: Install MySQL server
      yum:
         name: mariadb-server
         state: present

    - name: Installing dependencies pymysql
      yum:
        name: python3-PyMySQL
        state: present

    - name: Start & Enable maridb service
      service:
         name: mariadb
         state: started
         enabled: yes
    
    - name: Create a new database 
      mysql_db:
        name: "{{dbname}}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
      register: dbdatabase

    - name: Create a database user
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
      register: dbuser

    - name: print dbdatabse output
      debug:
        var: dbdatabase

    - name: print dbuser output
      debug:
        var: dbuser
